- color: d73a4a
  description: Something isn't working
  name: bug
- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation
- color: a2eeef
  description: New feature or request
  name: enhancement
- color: b60205
  description: An urgent pull request to look
  name: emergency
- color: f9d0c4
  description: Refactor Code
  name: refactor
- color: 1d76db
  description: Test Code
  name: test
- color: c2e0c6
  description: Create Release Branch
  name: test
