- color: d73a4a
  description: Something isn't working
  name: bug
- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation
- color: a2eeef
  description: New feature or request
  name: enhancement
- color: B60205
  description: An urgent pull request to look
  name: emergency
- color: F9D0C4
  description: Refactor Code
  name: refactor
- color: 1D76DB
  description: Test Code
  name: test
