name: 'Setup Poetry and Django'

description: 'Setup Django by using cache and Poetry'

# inputの箇所にpathを指定してあげるのはどうかな？
inputs:
  working-directory:
    description: 'working-directory of pyproject.toml'
    required: true
    default: application

runs:
  # compositeが必須
  using: 'composite'
  steps:
<<<<<<< HEAD:.github/actions/set-up-poetry/action.yml
    # https://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing
    # pycurl用のパッケージをインストール
    - name: Install packages for pycurl
      run: sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev
      shell: bash
=======
    - name: Install packages for pycurl
      run: sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev-is-python3
      shell: bash
      working-directory: ${{ inputs.working-directory }}
>>>>>>> develop:.github/actions/set-up-django/action.yml
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Use cache dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install Packages
      run: poetry install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Execute Migration
      run: |
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
