# Generated by Django 4.2.1 on 2023-06-01 11:36

import uuid

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="address",
            table_comment="住所",
        ),
        migrations.AlterModelTableComment(
            name="customer",
            table_comment="システムユーザ",
        ),
        migrations.AlterModelTableComment(
            name="customerphoto",
            table_comment="お客様の画像",
        ),
        migrations.AlterModelTableComment(
            name="user",
            table_comment="システムユーザ",
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.ForeignKey(
                db_comment="住所ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="application.address",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="birthday",
            field=models.DateField(db_comment="誕生日"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(
                db_comment="お客様ID",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="kana",
            field=models.CharField(db_comment="カナ氏名", max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(db_comment="氏名", max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_no",
            field=models.CharField(
                blank=True,
                db_comment="電話番号",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{11}$", "11桁の数字を入力してください。"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_comment="作成日"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_comment="メールアドレス", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_number",
            field=models.CharField(
                db_comment="社員番号",
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^[0-9]{8}$")
                ],
                verbose_name="社員番号",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                db_comment="システムユーザID",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveIntegerField(
                choices=[(0, "Management"), (1, "General"), (2, "Part Time")],
                db_comment="システムユーザのロール",
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_comment="更新日"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_comment="ユーザ名",
                max_length=150,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
            ),
        ),
    ]
