# Generated by Django 4.2.1 on 2023-06-01 11:38

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import application.utils.customer_storage


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_alter_address_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="house_no",
            field=models.CharField(db_comment="丁・番地", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                db_comment="住所ID",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="municipalities",
            field=models.CharField(db_comment="市区町村", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="other",
            field=models.CharField(
                blank=True, db_comment="その他(マンション名など)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="post_no",
            field=models.CharField(
                db_comment="郵便番号",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{7}$", "7桁の数字を入力してください。"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="prefecture",
            field=models.CharField(db_comment="都道府県", max_length=255),
        ),
        migrations.AlterField(
            model_name="customerphoto",
            name="customer",
            field=models.ForeignKey(
                db_comment="お客様ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="application.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerphoto",
            name="id",
            field=models.UUIDField(
                db_comment="お客様の写真ID",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customerphoto",
            name="photo",
            field=models.ImageField(
                db_comment="写真",
                storage=application.utils.customer_storage.CustomerStorage(),
                upload_to="customer_photo",
            ),
        ),
    ]
