# Generated by Django 4.2.1 on 2023-06-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0003_alter_address_house_no_alter_address_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="customer",
            table_comment="お客様",
        ),
    ]
