# name: Format Python Code
# on: [pull_request]
# jobs:
#   format-code:
#     name: Use Black and Isort
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
#       - name: Order imports correctly using isort
#         uses: isort/isort-action@master
#         with:
#           sort-paths: "application/"
#       - name: Format code to pep8 style using black
#         # uses: rickstaa/action-black@v1
#         # with:
#         #   black_args: "application/"
#       # - name: Check files using black formatter
#         uses: psf/black@stable
#         with:
#           # options: "--preview"
#           src: "application/"
#       # - name: Annotate diff changes using reviewdog
#       #   if: steps.action_black.outputs.is_formatted == 'true'
#       #   uses: reviewdog/action-suggester@v1
#       #   with:
#       #     tool_name: blackfmt
