name: Test Service Container
on:
  pull_request:
    branches-ignore:
      - "release/**"

env:
  DEBUG: "True"
  DJANGO_SETTINGS_MODULE: project.settings
  SECRET_KEY: django
  MYSQL_DATABASE: django-db
  MYSQL_USER: django
  MYSQL_PASSWORD: django
jobs:
  test:
    name: Run Test Code
    runs-on: ubuntu-20.04
    services:
      db:
        image: mysql:8.0.31
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: django-db
          MYSQL_USER: django
          MYSQL_PASSWORD: django
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Inspect env
        run: env
      - name: Grant privileges to user
        run: |
          mysql --protocol=tcp -h 127.0.0.1 -P 3306 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'django'@'%'; FLUSH PRIVILEGES;"
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - name: Run migration
        run: |
          poetry run python manage.py makemigrations
          poetry run python manage.py migrate
      - name: Run tests
        run: poetry run pytest
